#Numpy

In [1]:
import numpy as np
a = np.array([1,2,3])

In [5]:
c1 = np.arange(0,10,1)
c1 = c1.reshape(2,5)
c1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
c2 = c1.ravel()
c3 = c1.flatten()

In [12]:
print(c1.dtype)
c1 = c1.astype(np.float32)
c1.dtype

int32


dtype('float32')

In [14]:
c1[:,2]

array([2., 7.], dtype=float32)

In [21]:
print(c1)
#参照渡し
c3 = c1
print(c3)
c3[1][1] = 8
print(c3)
print(c1)


[[0. 1. 2. 3. 4.]
 [5. 8. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 8. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 8. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 8. 7. 8. 9.]]


In [24]:
print(c1)
#コピー渡し
c3 = c1.copy()
print(c3)
c3[1][1] = 10
print(c3)
print(c1)

[[0. 1. 2. 3. 4.]
 [5. 8. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 8. 7. 8. 9.]]
[[ 0.  1.  2.  3.  4.]
 [ 5. 10.  7.  8.  9.]]
[[0. 1. 2. 3. 4.]
 [5. 8. 7. 8. 9.]]


In [29]:
f = np.random.seed(123)
f = np.random.random((3,2))
f

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [30]:
f = np.random.seed(123)
f = np.random.rand(3,2)
f

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [31]:
np.random.uniform(0,5,size=(5,4))

array([[4.90382099, 3.42414869, 2.40465951, 1.96058759],
       [1.71589008, 3.64524854, 2.19286122, 0.29838948],
       [1.99022128, 3.68997703, 0.91245865, 0.87725878],
       [2.65775687, 2.65913794, 3.17200479, 4.24715897],
       [3.62227662, 3.05511755, 3.61221691, 1.61479457]])

In [33]:
f = np.random.seed(123)
np.random.randn(4,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.full((3,3),np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [43]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
a1 = np.arange(5)
a2 = np.arange(6,11,1)
print(a1)
print(a2)

[0 1 2 3 4]
[ 6  7  8  9 10]


In [48]:
np.concatenate([a1,a2],axis=0)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10])

In [50]:
b = np.vstack([a1,a2])

In [51]:
b.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10]])

In [53]:
b=[[-3,-2,-1],[0,1,2]]
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [55]:
np.sin(b)

array([[-0.14112001, -0.90929743, -0.84147098],
       [ 0.        ,  0.84147098,  0.90929743]])

In [56]:
np.log(b)

C:\Users\secre\AppData\Local\Temp\ipykernel_19116\4200754868.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)
C:\Users\secre\AppData\Local\Temp\ipykernel_19116\4200754868.py:1: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([[       nan,        nan,        nan],
       [      -inf, 0.        , 0.69314718]])

In [57]:
np.log10(b)

C:\Users\secre\AppData\Local\Temp\ipykernel_19116\3416214235.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(b)
C:\Users\secre\AppData\Local\Temp\ipykernel_19116\3416214235.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(b)


array([[    nan,     nan,     nan],
       [   -inf, 0.     , 0.30103]])