In [24]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [25]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.31086826,  0.41384208, -0.2781095 ,  0.4663476 , -0.25994915,
         0.23901579,  0.42836085, -0.80680954,  0.08879168,  0.24034026]],
      dtype=float32)

In [26]:
tf.nn.softmax(predictions).numpy()

array([[0.06671953, 0.13771798, 0.06894137, 0.14514214, 0.0702048 ,
        0.11562841, 0.13973206, 0.04063202, 0.0995    , 0.11578166]],
      dtype=float32)

In [27]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [28]:
loss_fn(y_train[:1], predictions).numpy()

2.1573734

In [29]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [30]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2959 - accuracy: 0.9132
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1404 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1043 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0866 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0726 - accuracy: 0.9773


In [31]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0804 - accuracy: 0.9756 - 502ms/epoch - 2ms/step


[0.08038889616727829, 0.975600004196167]

In [32]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [33]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.91747555e-08, 8.28499847e-09, 3.51940180e-05, 3.53267475e-04,
        4.59483536e-12, 2.15506031e-08, 5.89576199e-14, 9.99605715e-01,
        3.14944458e-07, 5.41023110e-06],
       [5.96496741e-10, 3.65157830e-05, 9.99960780e-01, 2.71889826e-06,
        1.78554836e-16, 1.25833610e-08, 8.44472992e-10, 2.68050122e-13,
        5.77147894e-08, 8.43164378e-14],
       [8.65697203e-08, 9.99746382e-01, 1.01089157e-04, 3.97352187e-06,
        2.68130111e-06, 3.08987978e-07, 1.14933819e-05, 1.03552666e-04,
        3.02453263e-05, 9.79422907e-08],
       [9.99572217e-01, 2.10884128e-08, 2.85604874e-05, 6.17766659e-07,
        1.13876672e-06, 1.02202739e-05, 3.77740187e-04, 6.11156383e-06,
        1.76989062e-07, 3.10928840e-06],
       [5.92292054e-07, 2.07397388e-09, 2.40128475e-06, 7.86769192e-08,
        9.99178112e-01, 4.47085512e-07, 8.80969128e-06, 2.67832729e-05,
        3.71748729e-06, 7.79092545e-04]], dtype=float32)>